### ISSUE TITLE
Feature Request: Extend argument parsing support for pflags.StringArray

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-plugin-sdk#54]
Currently:
currently string slice arguments are handled as pflags.StringSlice and this treats strings as CSV comma delimited strings making it possible to use a single argument call and extract a multiple value string slice from a single string.
Problem:
Automatic use of commas as separates is not always appropriate

Solution:
optionally allow arguments to be treated as pflags.StringArray, which does not automatically used the comma delimited string splitting.  

Straw Implementation:
Extend the option struct with a new boolean to treat string slice  as a pflags.StringArray in setupFlag() function

**Comment by echlebek** [comment]
Done!
